import React from "react";
import CountingTrumpsTrainer from "../Counting/CountingTrumpsTrainer";

/**
 * Bidding practice: opening (1–5) and responding (6–10). Uses CountingTrumpsTrainer with question-only flow (no tricks).
 */
const BIDDING_PUZZLES = [
  // --- Opening: Do you open the bidding? (1–5) ---
  {
    id: "bid1-1",
    difficulty: 1,
    title: "Opening (1): Do you open?",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Do you open the bidding?",
      promptThemeTint: "points",
      videoUrlBeforeStart: "https://www.youtube.com/embed/0vLi6n5efks",
      customPrompts: [
        {
          id: "bid1-1-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "This series is about training your eye to recognise what a \"good\" and \"bad\" hand look like. Even at a glance, it will start to stick out to you.\n\nWith minimal effort you want to know whether to open the hand or not.",
          videoUrl: "",
        },
        {
          id: "bid1-1-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Do you open this?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "no",
          noContinue: true,
          revealText:
            "No. This hand has 11 points. We typically open most 12-point hands, but when we have less than that we need to use judgment.\n\nThis is what I would call a \"bad\" 11. The hand has several flaws:\n\n✗ There are no 10s and 9s.\n\n✗ The hand is very balanced, 4333.\n\n✗ The honours are scattered everywhere — you don't have a collection of honours/strength in any suit.\n\nWithout doubt this is a pass.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "QJ2", H: "K32", D: "Q432", C: "K32" },
    },
    rounds: [],
  },
  {
    id: "bid1-2",
    difficulty: 1,
    title: "Opening (2): Do you open?",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Do you open the bidding?",
      promptThemeTint: "points",
      videoUrlBeforeStart: "https://www.youtube.com/embed/fYNlZS3KLa0",
      customPrompts: [
        {
          id: "bid1-2-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Do you open this?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes. In contrast to the previous hand, this one has:\n\n✓ More shape — 4432 rather than 4333.\n\n✓ Honour cards nicely clustered in two suits; concentrated strength works better than scattered. \"They work better together.\"\n\n✓ Length and/or strength in the majors is a good thing; here you have both.\n\n✓ Quality cards — an Ace and two Kings.\n\n✓ Excellent intermediate cards (10s and 9s) to complement your long, strong suits.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "AKT2", H: "KJT2", D: "65", C: "432" },
    },
    rounds: [],
  },
  {
    id: "bid1-3",
    difficulty: 1,
    title: "Opening (3): Do you open?",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Do you open the bidding?",
      promptThemeTint: "points",
      videoUrlBeforeStart: "https://www.youtube.com/embed/8NFCsnOk_mc",
      customPrompts: [
        {
          id: "bid1-3-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Do you open this?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes. We have to draw the line somewhere, but it might have to be at 9 points. This hand has excellent shape; the 6-card suit is robust. It is unbalanced, 6313, which gives it even better prospects of succeeding in a suit contract.\n\nYou could open a weak 2 if you play that, but you could argue that this hand fits the bill of an opening hand — the Aces and Kings, and the overall \"purity\" (cards in the right places/suits) is so good.\n\nContrast this hand with, say, ♠Q9xxxx ♥xxx ♦A ♣KJx — both hands are 10 points, yet our actual hand is leagues better.\n\nEven though spades is the likely contract if your side is to win the bidding, believe it or not this hand could even be an excellent dummy if partner has hearts or even clubs. More on this to come.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "AKT982", H: "KT2", D: "6", C: "432" },
    },
    rounds: [],
  },
  {
    id: "bid1-4",
    difficulty: 1,
    title: "Opening (4): Should you open?",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Do you open the bidding?",
      promptThemeTint: "points",
      videoUrlBeforeStart: "https://www.youtube.com/embed/6wUceGvMFZA",
      customPrompts: [
        {
          id: "bid1-4-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Should you open this?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "no",
          noContinue: true,
          revealText:
            "No. There has to be a cutoff. At the end of the day it is a 10-point hand that is balanced and not exceptional. It is not a bad hand — in fact it's very close to opening quality.\n\nPlus points include:\n\n✓ A strong 5-card suit with intermediate card(s).\n✓ Kings are good — better than Queens and Jacks typically.\n✓ No points in the shortage (doubleton) is often a good thing.\n\nNegatives include:\n\n✗ No Aces.\n✗ Simply not enough points — draw the line at 10 usually.\n✗ Somewhat balanced, 5332 — 5431 or 5521 becomes more attractive to open.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KJT98", H: "K32", D: "KT2", C: "65" },
    },
    rounds: [],
  },
  {
    id: "bid1-5",
    difficulty: 1,
    title: "Opening (5): Do you open? (Bobby's hand)",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Do you open the bidding?",
      promptThemeTint: "points",
      videoUrlBeforeStart: "https://www.youtube.com/embed/siYxTzj7eCo",
      customPrompts: [
        {
          id: "bid1-5-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Do you open this?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: ["yes", "no"],
          noContinue: true,
          revealText:
            "This is a famous hand, a bit of a trick question. Yes and No are both good answers. In general I would suggest against opening 8-point hands, but it is worth understanding the rationale at least.\n\nBob Richman, one of Australia's best ever players (although he wasn't born in Australia), once opened this exact hand. Bobby was later asked by someone why or how he opened that and he responded something like \"Don't tell your mother.\"\n\nWhat was Bobby's reason to open such a low HCP (high card point) hand?\n\n✓ Shapely 5521 is a big asset if you end up declaring the hand in a suit.\n✓ Both majors — the hand has both majors, giving you good prospects of finding a major suit part-score or game.\n✓ Aces are the boss card (and best card); also the 10s and 9s pad the suits up a lot, to make up for the lack of HCP.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "AT982", H: "AT832", D: "65", C: "2" },
    },
    rounds: [],
  },
  // --- Responding (6–10) ---
  {
    id: "bid1-6",
    difficulty: 1,
    title: "Responding (6): Partner opens 1♥",
    trumpSuit: "H",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♥ P ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "You are responder, what will you do?",
      promptThemeTint: "respond",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/LrGvzkV9WMI",
      customPrompts: [
        {
          id: "bid1-6-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText: "Partner has opened; your only job here is to describe your hand.",
          videoUrl: "",
        },
        {
          id: "bid1-6-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Your bid?",
          options: [
            { id: "1s", label: "1♠" },
            { id: "2h", label: "2♥" },
            { id: "pass", label: "Pass" },
            { id: "other", label: "Something else" },
          ],
          expectedChoice: "2h",
          noContinue: true,
          revealText:
            "I like to bid 2♥. There is a golden rule of bridge: \"Always support partner\". Without that rule, we are lost.\n\nIf I see my opponents break this rule, I smile and know it will be an easy game.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KT982", H: "QJ7", D: "6", C: "8752" },
    },
    rounds: [],
  },
  {
    id: "bid1-7",
    difficulty: 1,
    title: "Responding (7): West 1♥, North 1♠ — your bid (East)",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "W",
    declarerCompass: "E",
    viewerCompass: "E",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♥ 1♠ ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "You are responder, what will you do?",
      promptThemeTint: "respond",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/H4HYh8L9ZWg",
      customPrompts: [
        {
          id: "bid1-7-q1",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "What do you do?",
          options: [
            { id: "bid", label: "Bid something" },
            { id: "pass", label: "Pass" },
          ],
          expectedChoice: "bid",
          noContinue: false,
          revealText:
            "Bid something. Partner has overcalled; we have enough to respond (6 or 7+ points). We must always try to \"bid our hand\".",
          videoUrl: "",
        },
        {
          id: "bid1-7-q2",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "What do we bid?",
          options: [
            { id: "support", label: "Support partner" },
            { id: "1nt", label: "1NT" },
            { id: "other", label: "Something else" },
          ],
          expectedChoice: "other",
          noContinue: false,
          revealText:
            "Something else. We need 3 cards to support partner. \"Always support partner WHEN you have support.\" As for 1NT — that should show a spade stopper.",
          videoUrl: "",
        },
        {
          id: "bid1-7-q3",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "So what should we bid?",
          options: [
            { id: "suit", label: "One of our suits" },
            { id: "dbl", label: "Double (×)" },
          ],
          expectedChoice: "dbl",
          noContinue: true,
          revealText:
            "It is correct to double here. It conveys:\n\n(a) I have some points, say 6+.\n\n(b) I typically have the other two suits (takeout shape).",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "762", H: "K8", D: "KJT8", C: "QT92" },
    },
    rounds: [],
  },
  {
    id: "bid1-8",
    difficulty: 1,
    title: "Responding (8): 1♠ 3♦",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ 3♦ ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "You are responder, what will you do?",
      promptThemeTint: "respond",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/APpEVzvkdkU",
      customPrompts: [
        {
          id: "bid1-8-q1",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "You are considering making a bid. Firstly — does it matter what the opponent's 3♦ bid means?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "no",
          noContinue: false,
          revealText:
            "No. Basically it doesn't matter at all. Our goal is to bid our hand; often there is noise or chaos going on around us, but if possible we ignore the opponents and simply bid our hand.\n\nThis sounds strange, but as we do more and more problems, this idea will be clear.",
          videoUrl: "",
        },
        {
          id: "bid1-8-q2",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Let's say we did bid. What would we bid?",
          options: [
            { id: "support", label: "Support partner" },
            { id: "other", label: "Something else" },
          ],
          expectedChoice: "support",
          noContinue: false,
          revealText: "Support partner. Remember the golden rule — \"Always support partner.\"",
          videoUrl: "",
        },
        {
          id: "bid1-8-q3",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "So, finally, can we bid 3♠?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes we can. As a general rule, if we were able to raise partner to 2♠, we will typically take the push to 3♠ if needed.\n\nIt is a bit pushy, but it is better than the alternative of passing and pretending like you have nothing useful at all.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KT8", H: "AT7", D: "65", C: "87652" },
    },
    rounds: [],
  },
  {
    id: "bid1-9",
    difficulty: 1,
    title: "Responding (9): 1♠ 4♦",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ 4♦ ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "You are responder, what will you do?",
      promptThemeTint: "respond",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/DA7UluniZLo",
      customPrompts: [
        {
          id: "bid1-9-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "The opponents have made this difficult. Can we still follow the golden rule and support partner?",
          options: [
            { id: "4s", label: "Yes, bid 4♠" },
            { id: "pass", label: "No, pass" },
          ],
          expectedChoice: "pass",
          noContinue: true,
          revealText:
            "Pass — we have to stop somewhere unfortunately.\n\nLet's take a reality check. We have 7 points, partner may have say 12 points. That gives us a combined 19 points and an 8-card fit; we could be far too high bidding 4♠ with so little to spare.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KT8", H: "AT7", D: "65", C: "87652" },
    },
    rounds: [],
  },
  {
    id: "bid1-10",
    difficulty: 1,
    title: "Responding (10): 1♣ 1♥",
    trumpSuit: "C",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♣ 1♥ ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "You are responder, what will you do?",
      promptThemeTint: "respond",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/PukSNA8mqGo",
      customPrompts: [
        {
          id: "bid1-10-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "What do we bid?",
          options: [
            { id: "support", label: "Support partner" },
            { id: "spades", label: "Bid our spade suit" },
          ],
          expectedChoice: "spades",
          noContinue: true,
          revealText:
            "We should bid our spade suit. So why are we breaking the golden rule? There are two reasons:\n\n1. The main reason is — Majors are very important, especially spades. (More on this to come.) It's a good idea to try to find a major fit (hearts or spades).\n\n2. A 1♣ opening can often be 2 or 3 depending on your system. So raising clubs should really show 5 or even 6.\n\nEvery good bridge rule has a few exceptions here and there; that's what makes the game great!",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KT982", H: "76", D: "65", C: "AQ97" },
    },
    rounds: [],
  },
  // --- The modern 1NT opening (11–14) ---
  {
    id: "bid1-11",
    difficulty: 1,
    title: "1NT (11): 5242 with 5 spades",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "The modern 1NT opening",
      promptThemeTint: "1nt",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/X1wCFm0sPx0",
      customPrompts: [
        {
          id: "bid1-11-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "There are details about your hand that you may have never noticed before. These details change everything.\n\nThe 1NT opening is a good place to learn some of these \"details\" that I'm talking about.\n\nLet's turn you into an expert bidder.",
          videoUrl: "",
        },
        {
          id: "bid1-11-q1",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "You play a 15–17 No Trump. The shape of this hand is 5242, with a 5-card spade suit. Is that suitable for a 1NT opening?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: false,
          revealText:
            "Yes it can be suitable — however that does not mean we open all such shapes 1NT, even when they fit the correct point count. (As you will see in the upcoming examples.)\n\nThe hand shapes we often open 1NT are:\n\n• of course 4333\n• 4432\n• and the most normal 5-card suit shape: 5332\n• and finally we use our judgement (which we are now learning) with 5422",
          videoUrl: "",
        },
        {
          id: "bid1-11-q2",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Should we open this hand 1NT?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes, it is suitable. These are the reasons:\n\n1. Points in the short suits — This is one of your main reasons. On this hand 10 of 15 points are in your short suits. That strongly points towards No Trump.\n\n2. Your major suit quality is poor — Kxxxx is a very bad suit: only 1 honour card and no intermediate cards.\n\nReasons against:\n\n1. Always think twice with a 5-card major.\n\nA further comment: With a 5-card minor, we are more likely to open 1NT, although we still look at our points in the short suits.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "K9842", H: "AQ", D: "QT43", C: "AT" },
    },
    rounds: [],
  },
  {
    id: "bid1-12",
    difficulty: 1,
    title: "1NT (12): Stacked in the minors",
    trumpSuit: "D",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "The modern 1NT opening",
      promptThemeTint: "1nt",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/8kDxMREow_A",
      customPrompts: [
        {
          id: "bid1-12-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "The modern way is to open 1NT a lot more than we did in the past. It has a lot of advantages — one big one is to \"get your hand off your chest\" in a single bid. In general that is a VERY good principle, but it is not the end of the story.",
          videoUrl: "",
        },
        {
          id: "bid1-12-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Is this hand suitable for a 1NT opening?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "no",
          noContinue: true,
          revealText:
            "No. This is not suitable. The main giveaway is that your short suits do not have any points in them, and your minor suits are excellent.\n\nThe hand is very stacked in the minors; it is appropriate to open 1♦ and rebid 2♣, giving partner an accurate picture of your assets.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "43", H: "32", D: "AKT82", C: "AKJ2" },
    },
    rounds: [],
  },
  {
    id: "bid1-13",
    difficulty: 1,
    title: "1NT (13): 5332 with nice spades",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "The modern 1NT opening",
      promptThemeTint: "1nt",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/GedUP68ZQ8I",
      customPrompts: [
        {
          id: "bid1-13-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Is this hand suitable for 1NT?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes, it is — despite having a very nice spade suit and a small doubleton. When it comes to 5332 hands, we basically always open 1NT if we are in the correct point range. The advantage of opening 1NT and getting your hand \"off your chest\" is too big to talk yourself out of.\n\nWe only look at the doubletons when we are 5422.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "AKT92", H: "43", D: "AK2", C: "JT2" },
    },
    rounds: [],
  },
  {
    id: "bid1-14",
    difficulty: 1,
    title: "1NT (14): 14 points and a 5-card suit",
    trumpSuit: "H",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "The modern 1NT opening",
      promptThemeTint: "1nt",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/OJd8b--QDBo",
      customPrompts: [
        {
          id: "bid1-14-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText: "What about 14-point hands?",
          videoUrl: "",
        },
        {
          id: "bid1-14-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "This hand only has 14 points. Does that disqualify it from opening 1NT?",
          options: [
            { id: "suitable", label: "Suitable for 1NT" },
            { id: "not", label: "Not suitable" },
          ],
          expectedChoice: "suitable",
          noContinue: true,
          revealText:
            "It is suitable for 1NT. Despite only having 14 high card points, this hand to me looks a lot stronger. The reasons are:\n\n1. It has a 5-card suit. We typically can add 1 point for a 5-card suit.\n\n2. It has very good intermediate cards (10s and 9s).\n\nIf I'm being honest, to me this hand looks closer to 16 points than it does 14 points.\n\nPoint count is a very good start, but it is only a start.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KT", H: "AQT92", D: "AJ9", C: "T42" },
    },
    rounds: [],
  },
  {
    id: "bid1-15",
    difficulty: 1,
    title: "1NT (15): 14 points — upgrade to 15?",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "The modern 1NT opening",
      promptThemeTint: "1nt",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/VSm58Q0IU14",
      customPrompts: [
        {
          id: "bid1-15-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "This hand has the right shape for 1NT, with only 14 high card points. Can you upgrade this one to 15?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "no",
          noContinue: true,
          revealText:
            "No, I would not upgrade this one. The 5-card suit is bare, making it an unlikely source of extra tricks.\n\nIn general, good hands have \"clusters of points\", particularly in the long suits. This hand does not have much at all in its long suits. It has 2 points in its long suit, and 5 points in its shortest suit.\n\nThis is not a good hand — don't upgrade it.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "Q9842", H: "KQ", D: "Q32", C: "AJ2" },
    },
    rounds: [],
  },
  {
    id: "bid1-16",
    difficulty: 1,
    title: "1NT (16): Singleton in 1NT?",
    trumpSuit: "H",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "The modern 1NT opening",
      promptThemeTint: "1nt",
      newUntil: "2026-04-15",
      videoUrlBeforeStart: "https://youtube.com/shorts/Jrz2zRRlP5g",
      customPrompts: [
        {
          id: "bid1-16-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "This hand has a singleton. Would this ever qualify as a modern 1NT?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes, it qualifies as 1NT. The top players in the world are doing something that 20–30 years ago would have been unthinkable — opening 1NT with a singleton.\n\nDon't get carried away with this concept: they are only doing it with a singleton King. A singleton Ace is a completely different story, and I strongly advise against that.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "K32", H: "K", D: "AQT2", C: "AT842" },
    },
    rounds: [],
  },
  {
    id: "bid1-17",
    difficulty: 1,
    title: "1-level overcalls (17): A good suit at the one level",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♥ ?",
    vulnerability: "None Vul",
    shownHands: {
      DECLARER: { S: "AK1092", H: "3", D: "T987", C: "432" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "1-level overcalls",
      promptThemeTint: "active",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllWhite: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/F4HW3pNwKoo",
      customPrompts: [
        {
          id: "bid1-17-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##The old shorthand##\n\nOvercalls were often taught as 10+ points and a 5+ card suit. That still has its place — but exceptions are common.\n\n##What we'll do##\n\nBy example: a few ideas for 1-level overcalls.",
          videoUrl: "",
        },
        {
          id: "bid1-17-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "What do you do with this hand?",
          options: [
            { id: "pass", label: "Pass" },
            { id: "1s", label: "Overcall 1♠" },
          ],
          expectedChoice: "1s",
          noContinue: false,
          revealText:
            "[[ALERT]]\nBid 1♠ — a one-level overcall.\n[[/ALERT]]\n\nYou have only 7 HCP, but suit quality and shape carry the hand.\n\n##The useful rule##\n\n##At the 1 level, always consider overcalling a good suit.##\n\n• Outside singleton (♥3) → competing is more attractive.\n• Real spade suit (♠AK1092) → you want a voice in the auction.",
          videoUrl: "",
        },
        {
          id: "bid1-17-minimum",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Rough minimum##\n\n• A suit like ♠AQ1092 is a sensible floor for many pairs.\n• Below ~6 HCP can be pushing — agree with partner what you'll tolerate.\n\nExperts sometimes stretch lower; that's a topic for later.",
          videoUrl: "",
        },
        {
          id: "bid1-17-partnership",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Why this matters##\n\nImportant implications follow from light overcalls.\n\n[[ALERT]]\n**You need to have a discussion with your partner.**\n[[/ALERT]]\n\n##Partnership expectations##\n\nBridge runs on shared agreements. If partner knows you may hold only ~7 HCP on a bad day, they should be careful with thin 12–13 counts — often invite, don't blast.",
          videoUrl: "",
        },
        {
          id: "bid1-17-wrap",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Big picture##\n\nIt can sound risky — yet the best pairs find that the downsides of overcalling are usually smaller than the upsides. It tends to work.\n\n##At the table##\n\n• Listen to the whole auction: when opponents show a lot and you have values, remember partner might only have that light 7-point overcall.\n• Stay sensible — not every strong-looking spot is a slam try.\n\nGive it a try!",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-18",
    difficulty: 1,
    title: "1-level overcalls (18): Bad suit — pass the balanced misfit",
    trumpSuit: "D",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♣ ?",
    vulnerability: "None Vul",
    shownHands: {
      DECLARER: { S: "Q2", H: "Q76", D: "J7532", C: "KQ3" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "1-level overcalls",
      promptThemeTint: "active",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllWhite: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/OAX93O9g3qQ",
      customPrompts: [
        {
          id: "bid1-18-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "How do you handle this hand?",
          options: [
            { id: "pass", label: "Pass" },
            { id: "1d", label: "1♦" },
          ],
          expectedChoice: "pass",
          noContinue: false,
          revealText:
            "[[ALERT]]\nPass is correct.\n[[/ALERT]]\n\n##Two reasons##\n\n• Suit quality — think twice with bad suits. Diamonds is your worst suit!\n• Balanced is bad — any balanced hand without a singleton is not an exciting overcalling prospect.",
          videoUrl: "",
        },
        {
          id: "bid1-18-follow",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Points vs texture##\n\nThis hand has 10 HCP, but the values are poor — scattered, not concentrated in the long suit.\n\n• No Aces\n• No 10s or 9s (intermediates matter a lot)\n\nThat's a lot to digest — with repetition you'll build the skill of recognising bad hands vs good hands.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-19",
    difficulty: 1,
    title: "1-level overcalls (19): J10xxx — when the suit plays bigger",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♣ ?",
    vulnerability: "None Vul",
    shownHands: {
      DECLARER: { S: "J10987", H: "A54", D: "K102", C: "32" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "1-level overcalls",
      promptThemeTint: "active",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllWhite: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/eMqvRa3H8PQ",
      customPrompts: [
        {
          id: "bid1-19-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Do we make a bid here? Is it similar to the previous hand?",
          options: [
            { id: "pass", label: "Pass" },
            { id: "1s", label: "1♠" },
          ],
          expectedChoice: "1s",
          noContinue: false,
          revealText:
            "[[ALERT]]\nBid 1♠.\n[[/ALERT]]\n\nTo me 1♠ is an easy choice here, even though it is weaker in points than the previous hand, and even though it is balanced — which I have called bad (and I meant it!). So why does this one still qualify?\n\n##The short version##\n\nThe spade suit plays bigger than it looks, your values sit well, and one-level is cheap.",
          videoUrl: "",
        },
        {
          id: "bid1-19-why",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Why this one is different##\n\n• Rule: 10s and 9s carry a lot of weight in long suits. J10xxx is a lot better than Jxxxx — the suit is not as bad as it looks.\n\n• The outside cards are nice: Aces and Kings in the short suits.\n\n✓ No points in our short suits — this is a very big positive.\n\n• Balanced is bad, and I meant it — but it is not fatal. We do not want to talk ourselves out of bidding too often.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-20",
    difficulty: 1,
    title: "1-level overcalls (20): 7 points, all vul — still compete?",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♣ ?",
    vulnerability: "All Vul",
    shownHands: {
      DECLARER: { S: "K10987", H: "2", D: "A10982", C: "32" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "1-level overcalls",
      promptThemeTint: "active",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllRed: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/ayQv94xbDyY",
      customPrompts: [
        {
          id: "bid1-20-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Only 7 points and you are vulnerable — would you bid here?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: false,
          revealText:
            "[[ALERT]]\nYes — competing is still right.\n[[/ALERT]]\n\nDespite only 7 points and being vulnerable, the shape and suit quality make this hand worth a bid.",
          videoUrl: "",
        },
        {
          id: "bid1-20-why",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Reasons why##\n\n• I've tried to make those 10s and 9s stand out — they change everything. Seriously.\n\n• Your points are limited, but they are in Aces and Kings.\n\n• More important than how many points you have is where they sit: nicely placed in your long suits.\n\n• 5–5 shape is quite distributional — it is a long way from 5332.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-21",
    difficulty: 1,
    title: "1-level overcalls (21): Quick check — three questions",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: true,
      hideBiddingHand: true,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "Quick check",
      promptThemeTint: "active",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      hidePlayDecisionHeading: true,
      customPrompts: [
        {
          id: "bid1-21-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Quick summary##\n\nThis is a short wrap-up — we'll ask you three questions.\n\nTake your best guess, then read the notes — same style as the rest of this series.",
          videoUrl: "",
        },
        {
          id: "bid1-21-q1",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "What is the minimum high-card points you would aim for on a 1-level overcall?",
          options: [
            { id: "10plus", label: "10+" },
            { id: "6plus", label: "6+" },
            { id: "3plus", label: "3+" },
          ],
          expectedChoice: "6plus",
          noContinue: false,
          revealText:
            "[[ALERT]]\nAbout 6+ HCP is a sensible floor to aim for.\n[[/ALERT]]",
          videoUrl: "",
        },
        {
          id: "bid1-21-bridge1",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Point count##\n\nWhile some top pairs are increasingly ignoring point count, I would say it is a good idea to limit your minimum to about 6+.\n\n(In later series we will look at times when you throw all standards out the window and ignore point count.)",
          videoUrl: "",
        },
        {
          id: "bid1-21-q2",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Is it better for us to have most of our points in the suit we overcall, or in the outside suits?",
          options: [
            { id: "scattered", label: "Better if points are scattered around" },
            { id: "concentrated", label: "Better if points are concentrated in the long suit" },
          ],
          expectedChoice: "concentrated",
          noContinue: false,
          revealText:
            "[[ALERT]]\nConcentrated in the long suit.\n[[/ALERT]]\n\nYou want your honours working in your long suit.",
          videoUrl: "",
        },
        {
          id: "bid1-21-after2",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Suit quality##\n\nThe main takeaway from today should be — look at your suit quality, it matters.\n\nSo you want the points in your long suit.",
          videoUrl: "",
        },
        {
          id: "bid1-21-q3",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Does it matter if my hand has a singleton or not?",
          options: [
            { id: "m1", label: "It doesn't matter much" },
            { id: "m2", label: "It matters a little — singletons are okay" },
            { id: "m3", label: "It matters a lot — singletons are excellent" },
          ],
          expectedChoice: "m3",
          noContinue: false,
          revealText:
            "[[ALERT]]\nIt matters a lot — singletons are excellent.\n[[/ALERT]]",
          videoUrl: "",
        },
        {
          id: "bid1-21-wrap",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Shape##\n\nSingletons matter a lot.\n\n##Balanced is bad## — repeat that once or twice, every day! You can afford to do less with balanced hands.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-22",
    difficulty: 1,
    title: "2-level overcalls (22): 5332 at the two level",
    trumpSuit: "D",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ ?",
    vulnerability: "All Vul",
    shownHands: {
      DECLARER: { S: "K102", H: "32", D: "AK1098", C: "Q76" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "2-level overcalls",
      promptThemeTint: "twoLevel",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllRed: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/zap0W7SAEBk",
      customPrompts: [
        {
          id: "bid1-22-intro",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "##Two-level overcalls##\n\nLet's look at a few examples — the rules build off the 1-level rules. If you understood those, a lot of these will make sense. However, there are some key differences.",
          videoUrl: "",
        },
        {
          id: "bid1-22-q1",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "This hand definitely has some good features — a nice full diamond suit, several Aces and Kings — should we overcall or not?",
          options: [
            { id: "pass", label: "Pass" },
            { id: "twoDiamonds", label: "2♦" },
          ],
          expectedChoice: "pass",
          noContinue: false,
          revealText:
            "[[ALERT]]\nPass!\n[[/ALERT]]\n\nAs a pretty good general rule — do not overcall 5332 shape on the 2 level!\n\nI think this often comes as a very big surprise to players.",
          videoUrl: "",
        },
        {
          id: "bid1-22-flavour",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "I hate to \"sit on my hands\" and not make a bid with 12+ points, but unfortunately this hand just does not fit the flavour of a two-level overcall.\n\nWe need a more shapely hand, and/or a six-card suit.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-24",
    difficulty: 1,
    title: "2-level overcalls (24): 10 points — enough for 2♦?",
    trumpSuit: "D",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♥ ?",
    vulnerability: "All Vul",
    shownHands: {
      DECLARER: { S: "32", H: "97", D: "A10832", C: "AQ32" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "2-level overcalls",
      promptThemeTint: "twoLevel",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllRed: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/ZbzfkJ8sR3k",
      customPrompts: [
        {
          id: "bid1-24-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Does this hand qualify for a 2-level overcall?",
          options: [
            { id: "yes2d", label: "Yes — bid 2♦" },
            { id: "pass", label: "No — Pass" },
          ],
          expectedChoice: "pass",
          noContinue: false,
          revealText:
            "[[ALERT]]\nNo.\n[[/ALERT]]\n\nDespite being unbalanced and having nice suits, this does not qualify.\n\nAs you can see, these standards might feel somewhat conservative. (Bridge at the highest level can look conservative in some situations and aggressive in others.)",
          videoUrl: "",
        },
        {
          id: "bid1-24-guide",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "When we overcall a 5-card suit at the 2 level, we generally need:\n\n✓ Good opening hand or better\n\n✓ Distribution\n\nThis hand is only 2254 shape — doubletons in the majors — and it lacks values. Also the diamond suit is a bit bare.",
          videoUrl: "",
        },
        {
          id: "bid1-24-double",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "I like to apply this test after a 2-level overcall:\n\nIf I got penalty doubled on the 2 level, how would I feel? Personally I wouldn't feel too good with that diamond suit — I may only make 1 or 2 diamond tricks.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-25",
    difficulty: 1,
    title: "2-level overcalls (25): Six hearts — bid 2♥?",
    trumpSuit: "H",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ ?",
    vulnerability: "None Vul",
    shownHands: {
      DECLARER: { S: "2", H: "AJ9742", D: "A103", C: "863" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "2-level overcalls",
      promptThemeTint: "twoLevel",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllWhite: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/BXFYnIV2rKY",
      customPrompts: [
        {
          id: "bid1-25-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Is this enough to bid 2♥?",
          options: [
            { id: "bid2h", label: "I would bid 2♥" },
            { id: "pass", label: "I would Pass." },
          ],
          expectedChoice: "bid2h",
          noContinue: false,
          revealText:
            "[[ALERT]]\nYes — bid 2♥.\n[[/ALERT]]\n\nWhen it comes to 6-card suits, things shift — a lot. The rules move, and everything we thought we knew can be challenged.\n\nRule: With a good 6-card suit, typically bid it!",
          videoUrl: "",
        },
        {
          id: "bid1-25-suit",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "The suit is good: it has two honours, and it is reinforced with the 9 — that often makes all the difference.\n\nThe 6-card suit is the central factor. But still, in the context of 6-card suits we look at the same factors: good suits, well-placed cards, 10s and 9s, distribution, and so on.",
          videoUrl: "",
        },
        {
          id: "bid1-25-list",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "✓ It is distributional (it has a singleton).\n\n✓ It has Aces.\n\n✓ The side suit of ♦A103 is made better by the 10.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-26",
    difficulty: 1,
    title: "2-level overcalls (25): Bare clubs — still bid 2♣?",
    trumpSuit: "C",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ ?",
    vulnerability: "None Vul",
    shownHands: {
      DECLARER: { S: "32", H: "K2", D: "AK32", C: "A9876" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "2-level overcalls",
      promptThemeTint: "twoLevel",
      contractLabel: "Modern Overcalls",
      contractLabelBeforeStartOnly: true,
      auctionAllWhite: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/eyx0Eztx6Wg",
      customPrompts: [
        {
          id: "bid1-26-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "Would you bid 2♣ on this hand? The suit is very bare.",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: false,
          revealText:
            "[[ALERT]]\nYes.\n[[/ALERT]]\n\nYes — you have to bid: you have too much \"stuff\" to pass.",
          videoUrl: "",
        },
        {
          id: "bid1-26-a",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "Despite a bad suit, and not much distribution (no singleton), you cannot talk yourself out of bidding when you have so many points.",
          videoUrl: "",
        },
        {
          id: "bid1-26-b",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "However, this hand is not completely balanced — it is 2245. With 5332 I would consider passing, but even then I would consider mustering up a bid with 14 — it is just too much to pass if there is a sensible alternative.",
          videoUrl: "",
        },
      ],
    },
  },
  {
    id: "bid1-27",
    difficulty: 1,
    title: "2-level overcalls (26): Weak hearts — double instead?",
    trumpSuit: "D",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ ?",
    vulnerability: "None Vul",
    shownHands: {
      DECLARER: { S: "32", H: "J8532", D: "AKQ", C: "A32" },
    },
    rounds: [],
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      themeLabel: "2-level overcalls",
      promptThemeTint: "twoLevel",
      contractLabel: "East opens 1♠ — neither side vulnerable, you are South",
      contractLabelBeforeStartOnly: true,
      auctionAllWhite: true,
      hidePlayDecisionHeading: true,
      videoUrlBeforeStart: "https://youtube.com/shorts/moyEnVBNlEs",
      customPrompts: [
        {
          id: "bid1-27-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Is there a bid for this?",
          options: [
            { id: "pass", label: "Pass" },
            { id: "twoHearts", label: "2♥" },
            { id: "double", label: "Double" },
          ],
          expectedChoice: "double",
          noContinue: false,
          revealText:
            "[[ALERT]]\nDouble.\n[[/ALERT]]\n\nFirstly, once again we have too much \"stuff\" to pass if we have a sensible alternative.\n\nIn general it is better to bid a 5-card major than to double, but when it is so badly lacking texture, we can \"pretend\" it is a 4-card suit and just double.",
          videoUrl: "",
        },
        {
          id: "bid1-27-b",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "This is consistent with the idea that typically we do not overcall a 5332 on the 2 level — though often that shape may be a double instead.",
          videoUrl: "",
        },
      ],
    },
  },
  // Parked (hidden for now): former bid1-17 & bid1-18, and bid1-23 — see src/data/biddingDifficulty1Parked.js
  // --- Difficulty 2: Matchpoints (Club Duplicates) ---
  {
    id: "bid2-1",
    difficulty: 2,
    title: "Matchpoints (1): Invite or pass over 1NT?",
    newUntil: "2026-04-15",
    trumpSuit: "NT",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1NT P ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Let's look at how to score better at matchpoint scoring (Club Duplicates).",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "matchpoints",
      videoUrlBeforeStart: "https://www.youtube.com/embed/QiJjOLyc1Fc",
      customPrompts: [
        {
          id: "bid2-1-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "You pick up this hand and are deciding whether to invite by bidding 2NT or pass?",
          options: [
            { id: "2nt", label: "Invite, 2NT" },
            { id: "pass", label: "Pass" },
          ],
          expectedChoice: "pass",
          noContinue: true,
          revealText:
            "Pass is best.\n\n1. The most powerful idea in matchpoints is to \"go positive\". You get good matchpoints results by getting positive scores. We should always ask ourselves the question — what bidding decision will give me the best chance of coming out with a positive score?\n\n2. In general, I don't like inviting with 8 points opposite a 1NT, but especially in matchpoints. For me a balanced 8 points is typically a pass (Not always! there are some exceptions covered in other practice hands).",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "Q7", H: "KT4", D: "K953", C: "T842" },
    },
    rounds: [],
  },
  {
    id: "bid2-2",
    difficulty: 2,
    title: "Matchpoints (2): Invite 2NT or bid 3NT?",
    newUntil: "2026-04-15",
    trumpSuit: "NT",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1NT P ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Let's look at how to score better at matchpoint scoring (Club Duplicates).",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "matchpoints",
      videoUrlBeforeStart: "https://www.youtube.com/embed/PG8gsCnIpgw",
      customPrompts: [
        {
          id: "bid2-2-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Does it make sense to invite with 2NT on this hand or is it correct to just bid 3NT?",
          options: [
            { id: "3nt", label: "Bid 3NT" },
            { id: "2nt", label: "Bid 2NT" },
          ],
          expectedChoice: "2nt",
          noContinue: true,
          revealText:
            "2NT. Just invite with 2NT.\n\nFirstly, this is a very bad hand, 4333 and bad suits, honours spread everywhere, no intermediate cards. This hand is not good for taking tricks.\n\nSecondly, In duplicate pairs (matchpoint scoring) we want to be particularly careful — When we have the majority of the points we do not want to get too high and end up with a negative score.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "952", H: "K63", D: "Q874", C: "AJ5" },
    },
    rounds: [],
  },
  {
    id: "bid2-3",
    difficulty: 2,
    title: "Matchpoints (3): Compete over 2♠?",
    newUntil: "2026-04-15",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "E",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ P 2♠ P P ?",
    vulnerability: "Nil Vul",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Let's look at how to score better at matchpoint scoring (Club Duplicates).",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "matchpoints",
      auctionOpponentsRed: true,
      videoUrlBeforeStart: "https://www.youtube.com/embed/nAL-aloVfm0",
      customPrompts: [
        {
          id: "bid2-3-q1",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "I've been emphasising the importance of going positive.\n\nIf you knew for sure that you would get a minus score by entering the bidding (say for example ending up on the three level down 1), would that deter you?",
          options: [
            { id: "yes", label: "Yes that would deter me" },
            { id: "no", label: "No that wouldn't deter me" },
          ],
          expectedChoice: "no",
          noContinue: false,
          revealText:
            "We should be eager to bid, even expecting to go down in our contract. This feels like I am contradicting myself but I want to explain this simply.\n\nI mentioned before **when we have the majority of the points**, it is important that we do not squander that — we need to get a positive score.\n\nHOWEVER, things are very different when the points are divided evenly, or if the opponents have the slight majority. In that context, we want to compete for the part score, we are okay with going -1 or even -2 — that can be an excellent score if we aren't vulnerable.\n\nOne other main concept here — When the opponents have a fit, we want to fiercely compete for the part score. It is very wise to \"not let the opponents play on the two level with a fit\".",
          videoUrl: "",
        },
        {
          id: "bid2-3-q2",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "So would you bid on this rather bad looking hand?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "Yes, very clear yes. We want to fiercely compete when they have a fit. We actually have an excellent hand for that — nothing wasted in spades (their suit).\n\nWe have great shape for a takeout double. Remember we are balancing — we can expect partner to hold some stuff, the opponents stopped on the two level for a reason — our side has points.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "83", H: "KT72", D: "K954", C: "Q63" },
    },
    rounds: [],
  },
  {
    id: "bid2-4",
    difficulty: 2,
    title: "Matchpoints (4): Open light when not vulnerable?",
    newUntil: "2026-04-15",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "?",
    vulnerability: "Nil Vul",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Let's look at how to score better at matchpoint scoring (Club Duplicates).",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "matchpoints",
      auctionOpponentsRed: true,
      videoUrlBeforeStart: "https://www.youtube.com/embed/ebS-vAVOHjg",
      customPrompts: [
        {
          id: "bid2-4-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText:
            "This 10 point hand is probably not enough to open in most systems. Does duplicate/matchpoint scoring make a difference?",
          options: [
            { id: "less", label: "I am less likely to open this in duplicate scoring" },
            { id: "more", label: "I am more likely to open it." },
          ],
          expectedChoice: "more",
          noContinue: true,
          revealText:
            "More likely — but importantly, did you notice that our side is not vulnerable? When we are not vulnerable, the narrative should go like this:\n\n\"We want to enter the auction aggressively, both opening and overcalling, find a fit if we can, compete. We are okay with going 1 or 2 off in a partscore, its often a good score.\"\n\nHOWEVER, this mentality of get in there, be aggressive and compete when not vulnerable, has implications.\n\nIf we are going to bid 1 or even 2 points lighter than normal, Partner needs to know and:\n\n✓ Be on the same page\n✓ Not punish us for it.\n\nWhat does it mean to punish us? Check out the next training question.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "AKT73", H: "842", D: "KT6", C: "95" },
    },
    rounds: [],
  },
  {
    id: "bid2-5",
    difficulty: 2,
    title: "Matchpoints (5): Respond to 1♠ — invite or game?",
    newUntil: "2026-04-15",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ P ?",
    vulnerability: "Nil Vul",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Let's look at how to score better at matchpoint scoring (Club Duplicates).",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "matchpoints",
      auctionOpponentsRed: true,
      auctionPartnersGreen: true,
      videoUrlBeforeStart: "https://www.youtube.com/embed/whAQpZT7DLk",
      customPrompts: [
        {
          id: "bid2-5-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "North opens 1♠, pass by East. Do you bid 2♠, invite, or game force?",
          options: [
            { id: "2s", label: "2♠" },
            { id: "invite", label: "Invite" },
            { id: "game", label: "Game force" },
          ],
          expectedChoice: ["2s", "invite"],
          noContinue: true,
          revealText:
            "I would just bid 2♠. Inviting is acceptable but will score lower in the long run.\n\nThere are three reasons for that.\n\n1. This is a very bad 11 point hand — the next 5 problems are on hand evaluation and will revisit this hand.\n\n2. Matchpoints is about staying low and making your contracts. Getting too high and going down is a matchpoint sin.\n\n3. I don't want to punish partner for opening NV — I know we get in there aggressively.\n\nTo be a good matchpoint player, you need to learn to do less with your 11's and even bad 12's when partner opens NV.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "Q74", H: "J92", D: "A73", C: "KJ85" },
    },
    rounds: [],
  },
  {
    id: "bid2-6",
    difficulty: 2,
    title: "Hand evaluation (6): Feelings about this hand",
    newUntil: "2026-04-15",
    trumpSuit: "S",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♠ P ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Advanced hand evaluation",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "handEval",
      auctionAllWhite: true,
      videoUrlBeforeStart: "https://www.youtube.com/embed/IhA64-MOjAk",
      customPrompts: [
        {
          id: "bid2-6-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "North opens 1♠, Pass by East, your hand as South. Firstly, what are your feelings about this hand?",
          options: [
            { id: "bad", label: "Bad hand" },
            { id: "average", label: "Average, nothing special" },
            { id: "pretty", label: "Pretty good hand" },
          ],
          expectedChoice: "pretty",
          noContinue: false,
          revealText:
            "I like this hand for a few reasons.\n\n1. In diamonds the honours and intermediates are clustered, and the suit has length (4+ cards). That could easily become 3 or 4 tricks. I see a lot of potential in those diamonds!\n\n2. Outside of diamonds we have Aces which are excellent cards. More specifically, if you have a bare suit with just an Ace, it is perfectly fine as that Ace will certainly come in useful. Bare suits such as Qxxx can frequently be completely useless.\n\n3. In the trump suit we have Quacks — Queens and Jacks. Quacks are considered bad things typically, but in the trump suit they are typically excellent.",
          videoUrl: "",
        },
        {
          id: "bid2-6-summary",
          type: "INFO",
          atRoundIdx: -1,
          promptText:
            "In summary\n\n✓ \"Clustered\" honours are good things, like the diamond suit.\n✓ Queens and Jacks are excellent in the trump suit, not as good outside.\n✓ Aces are good everywhere. But unlike other cards, they work fine on their own — for example Axx is an asset whereas Qxx in a side suit can be worth very little.",
          videoUrl: "",
        },
        {
          id: "bid2-6-q2",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "So would you game force or invite?",
          options: [
            { id: "game", label: "Game force" },
            { id: "invite", label: "Invite" },
          ],
          expectedChoice: "game",
          noContinue: true,
          revealText:
            "I would game force for sure. The only time I would consider just inviting is in duplicate scoring, but even then I think game forcing is probably a better idea.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "QJ5", H: "A84", D: "KQT6", C: "932" },
    },
    rounds: [],
  },
  {
    id: "bid2-7",
    difficulty: 2,
    title: "Hand evaluation (7): 1NT opening?",
    newUntil: "2026-04-15",
    trumpSuit: "NT",
    contract: "—",
    dealerCompass: "S",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Advanced hand evaluation",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "handEval",
      auctionAllWhite: true,
      videoUrlBeforeStart: "https://www.youtube.com/embed/VwKRIT9XML8",
      customPrompts: [
        {
          id: "bid2-7-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "You play 15–17 1NT. Is this a simple 1NT opening?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "no",
          noContinue: true,
          revealText:
            "No. To me this is very clearly not good enough to open 1NT. If I had to put a point count on that hand, I would say it's worth about 13 at most.\n\nWhy is it such a downgrade?\n\n1. 4333 is not great shape.\n\n2. Honours are dense in the short suits, and long suits are bare — this is bad. Good hands have the opposite: strong long suits, and less or nothing in the short suits. \"We want our honours to be working hard in our long suits.\"\n\n3. No intermediate cards — these are very important! 10's and 9's make all the difference for trick taking.\n\n4. No Aces, lots of \"Quacks\" — Queens and Jacks.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "KQ4", H: "KQJ", D: "K752", C: "J93" },
    },
    rounds: [],
  },
  {
    id: "bid2-8",
    difficulty: 2,
    title: "Hand evaluation (8): Bid 5♣ over 4♠?",
    newUntil: "2026-04-15",
    trumpSuit: "C",
    contract: "—",
    dealerCompass: "N",
    declarerCompass: "S",
    viewerCompass: "S",
    visibleFullHandSeats: ["DECLARER"],
    auction: "1♣ 1♠ P 2♠ 4♣ 4♠ ?",
    promptOptions: {
      promptPlacement: "right",
      hideAuction: false,
      disableWarmupTrumpGuess: true,
      questionNumbers: [],
      contractLabel: "Advanced hand evaluation",
      contractLabelBeforeStartOnly: true,
      promptThemeTint: "handEval",
      auctionAllWhite: true,
      videoUrlBeforeStart: "https://www.youtube.com/embed/qw3n2tiYTq0",
      customPrompts: [
        {
          id: "bid2-8-q",
          type: "PLAY_DECISION",
          atRoundIdx: -1,
          promptText: "Would you make a bid to the 5 level?",
          options: [
            { id: "yes", label: "Yes" },
            { id: "no", label: "No" },
          ],
          expectedChoice: "yes",
          noContinue: true,
          revealText:
            "I would confidently bid 5♣. Why?\n\nFirstly I want to address the fact that I'm 4333, and I've been talking down these shapes. Everything is contextual in bridge. When partner is highly unbalanced, it becomes much less relevant whether you are balanced or not. In other words:\n\n**We want to slow down when both hands are balanced.**\n\nHowever\n\n**We don't want to be deterred by being balanced when partner is highly unbalanced.**\n\nLet's move on.\n\n##Our golden rule: always support partner!## We have probably a 10 or 11 card fit — let partner know, follow the golden rule.\n\nFinally, our points are excellent. The Queen in the trump suit is good, and an outside Ace is perfect. You have an excellent hand and should be confident to bid.",
          videoUrl: "",
        },
      ],
    },
    shownHands: {
      DECLARER: { S: "9732", H: "842", D: "A65", C: "Q94" },
    },
    rounds: [],
  },
];

export { BIDDING_PUZZLES };

function BiddingTrainer({ location }) {
  return (
    <CountingTrumpsTrainer
      puzzlesOverride={BIDDING_PUZZLES}
      trainerLabel="Bidding"
      categoryKey="bidding"
      location={location}
    />
  );
}

export default BiddingTrainer;
