export const PROBLEM_HANDS = [
  {
    id: "ph1",
    title: "Declarer #1",
    deal: {
      hands: {
        N: [
          { suit: "S", rank: "A" }, { suit: "S", rank: "3" }, { suit: "S", rank: "2" },
          { suit: "H", rank: "A" }, { suit: "H", rank: "5" }, { suit: "H", rank: "4" },
          { suit: "D", rank: "7" },
          { suit: "C", rank: "A" }, { suit: "C", rank: "K" }, { suit: "C", rank: "Q" },
          { suit: "C", rank: "T" }, { suit: "C", rank: "5" }, { suit: "C", rank: "4" },
        ],
        E: [
          { suit: "S", rank: "8" }, { suit: "S", rank: "Q" }, { suit: "S", rank: "J" },
          { suit: "H", rank: "2" },
          { suit: "D", rank: "A" }, { suit: "D", rank: "Q" }, { suit: "D", rank: "J" },
          { suit: "D", rank: "9" }, { suit: "D", rank: "8" }, { suit: "D", rank: "5" },
          { suit: "D", rank: "4" },
          { suit: "C", rank: "3" }, { suit: "C", rank: "2" },
        ],
        S: [
          { suit: "S", rank: "T" }, { suit: "S", rank: "9" }, { suit: "S", rank: "7" },
          { suit: "S", rank: "6" }, { suit: "S", rank: "5" }, { suit: "S", rank: "4" },
          { suit: "H", rank: "8" }, { suit: "H", rank: "7" },
          { suit: "D", rank: "T" }, { suit: "D", rank: "6" }, { suit: "D", rank: "3" },
          { suit: "D", rank: "2" },
          { suit: "C", rank: "7" },
        ],
        W: [
          { suit: "S", rank: "K" },
          { suit: "H", rank: "K" }, { suit: "H", rank: "Q" }, { suit: "H", rank: "J" },
          { suit: "H", rank: "T" }, { suit: "H", rank: "9" }, { suit: "H", rank: "6" },
          { suit: "H", rank: "3" },
          { suit: "D", rank: "K" },
          { suit: "C", rank: "J" }, { suit: "C", rank: "9" }, { suit: "C", rank: "8" },
          { suit: "C", rank: "6" },
        ],
      },
      dealer: "E",
      vul: "",
    },
    auction: [
      { seat: "E", call: { level: 3, strain: "D" } },
      { seat: "S", call: { kind: "pass" } },
      { seat: "W", call: { kind: "pass" } },
      { seat: "N", call: { kind: "double" } },
      { seat: "E", call: { kind: "pass" } },
      { seat: "S", call: { level: 3, strain: "S" } },
      { seat: "W", call: { kind: "pass" } },
      { seat: "N", call: { level: 4, strain: "D" } },
      { seat: "E", call: { kind: "pass" } },
      { seat: "S", call: { level: 4, strain: "S" } },
      { seat: "W", call: { kind: "pass" } },
      { seat: "N", call: { kind: "pass" } },
      { seat: "E", call: { kind: "pass" } },
    ],
    contract: { level: 4, strain: "S", declarer: "S", doubled: 0 },
    lead: { seat: "W", card: { suit: "H", rank: "K" } },
    intro: [
      "With the south hand, you simply bid 3S over the double. Some people might be tempted to bid 4S with 6 cards despite such few points. The biggest problem is that partner will not know you're so weak - if they raise your 4S to 6S, how are you feeling?",
      "Partner's 4D bid was a generic bid. It applies after the opponents preempt. It says 'I obviously have a good hand, I'm forcing the bidding up, but I don't have primary spade support (4 cards), I have a hand which might be okay for spades (3 card support) but otherwise I have another suit'.",
      "After all that the contract is 4S, your play.",
    ],
    solution: "(Solution to be added.)",
  },
  {
    id: "ph2",
    title: "Declarer #2",
    deal: {
      hands: {
        N: [
          { suit: "S", rank: "A" }, { suit: "S", rank: "3" }, { suit: "S", rank: "2" },
          { suit: "H", rank: "A" }, { suit: "H", rank: "K" }, { suit: "H", rank: "J" },
          { suit: "H", rank: "9" }, { suit: "H", rank: "4" },
          { suit: "D", rank: "A" }, { suit: "D", rank: "4" },
          { suit: "C", rank: "A" }, { suit: "C", rank: "5" }, { suit: "C", rank: "2" },
        ],
        E: [
          { suit: "S", rank: "K" }, { suit: "S", rank: "J" }, { suit: "S", rank: "6" },
          { suit: "H", rank: "5" },
          { suit: "D", rank: "9" }, { suit: "D", rank: "8" }, { suit: "D", rank: "6" },
          { suit: "D", rank: "3" }, { suit: "D", rank: "2" },
          { suit: "C", rank: "Q" }, { suit: "C", rank: "J" }, { suit: "C", rank: "T" },
          { suit: "C", rank: "3" },
        ],
        S: [
          { suit: "S", rank: "Q" }, { suit: "S", rank: "T" }, { suit: "S", rank: "9" },
          { suit: "S", rank: "8" }, { suit: "S", rank: "5" }, { suit: "S", rank: "4" },
          { suit: "H", rank: "Q" }, { suit: "H", rank: "8" }, { suit: "H", rank: "3" },
          { suit: "H", rank: "2" },
          { suit: "D", rank: "7" }, { suit: "D", rank: "5" },
          { suit: "C", rank: "K" },
        ],
        W: [
          { suit: "S", rank: "7" },
          { suit: "H", rank: "T" }, { suit: "H", rank: "7" }, { suit: "H", rank: "6" },
          { suit: "D", rank: "K" }, { suit: "D", rank: "Q" }, { suit: "D", rank: "J" },
          { suit: "D", rank: "T" },
          { suit: "C", rank: "9" }, { suit: "C", rank: "8" }, { suit: "C", rank: "7" },
          { suit: "C", rank: "6" }, { suit: "C", rank: "4" },
        ],
      },
      dealer: "",
      vul: "",
    },
    auction: [],
    contract: null,
    lead: null,
    intro: [],
    solution: "(Solution to be added.)",
  },
];
